### ISSUE TITLE
new option diff_context don't work

### ISSUE THREAD

**Issue by CudaText-addons** [CudaText-addons/cuda_differ#10]
new option diff_context doesn't work. It always uses the default value. 

maybe @veksha can see it, please?

**Comment by veksha** [comment]
> here `ctx.version(0) >= '0.6.8'` is always `False` (`ctx.version(0) == 0.6.10 2020-10-14`)
> 
> ```python
> def get_opt(key, def_val: tp.Any = ''):
>     return ctx.get_opt('differ.' + key, def_val, user_json=JSONFILE) \
>            if ctx.version(0) >= '0.6.8' \
>            else ctx.get_opt('differ.' + key, def_val)
> ```
> 
> so options were not read from `JSONFILE`. @Alexey-T , please help.

ctx.version(0) must return `0.6.10` for this comparison to work?
can this break something in other places (plugins)?

**Comment by Alexey-T** [comment]
seems version comparing was not needed. cud has cudax_lib (ctx) version updated long time ago. fixed..
