### ISSUE TITLE
Cuda default/user config affection

### ISSUE THREAD

**Issue by ThaiDat** [CudaText-addons/cuda_differ#11]
Repro steps:
- Install Cuda Differ
- Open Default/User config
- Scroll

Scrolling is now synchronized between two sides which is not true.

**Comment by veksha** [comment]
> Scrolling is now synchronized between two sides which is not true.

no sync on my side. only after "Differ: Refresh".

**Comment by Alexey-T** [comment]
to-fix for me.

**Comment by Alexey-T** [comment]
fix the synced scrolling of user+default configs by Differ. i didnt repro it yet. but i will run Differ and then open 2 configs. it must be visible?

**Comment by veksha** [comment]
> i will run Differ

what do you mean? run another 2 files to compare?

**Comment by Alexey-T** [comment]
- i first call differ to compare some crap files
- i need to see that after it, Differ affects 'user/def' pair

**Comment by veksha** [comment]
comparing simple files with Differ takes some long time (why?). maybe user quickly opens default/user config while Differ is working?

**Comment by Alexey-T** [comment]
fixed , seems. update the plugin (Addons Manager / Update) and test, pls.

**Comment by Alexey-T** [comment]
@veksha 

>comparing simple files with Differ takes some long time (why?)

possible reason

- slow work of python's difflib
- slow adding of editor-gaps to the file-pair and/or editor gutter marks

**Comment by ThaiDat** [comment]
> fixed , seems. update the plugin (Addons Manager / Update) and test, pls.

Verified as fixed
