### ISSUE TITLE
Files being compared are lost on restart

### ISSUE THREAD

**Issue by pintassilgo** [CudaText-addons/cuda_differ#13]
CudaText 1.86.5.0, Differ 2023.02.24.

I was comparing two files, but needed to restart CudaText (to try a new Beta build). After restarting, I lost the files being compared, they disappeared from CudaText. Since they were unsaved files, they were really lost.

If making differ able to handle session is a complex task, the quick workaround to prevent data loss is by automatically running `Differ > Back to separated tabs` when CudaText receives a command to exit, because files on separated tabs are correctly restored, so in next session users will need to do `Diff > Compare with` again, but at least nothing is lost.

**Comment by Alexey-T** [comment]
This is Cud's issue, not issue of plugin- please copy the post to Cud's Issues-page.

**Comment by Alexey-T** [comment]
It was the issue __of plugin__, sorry. fixed.

**Comment by Alexey-T** [comment]
>Should I open a new Issue for this?

Yes, please
