### ISSUE TITLE
Differ should not change title of tab

### ISSUE THREAD

**Issue by pintassilgo** [CudaText-addons/cuda_differ#16]
Let's say you have two open tabs, "Untitled 1" and "Untitled 2".

Using Rename plugin, you rename "Untitled 2" to "temp note".

Then you do Compare with "Untitled 1" and "temp note".

The title of the window when active tab is a comparison made by Differ should allow the user to recorgnize the name of original tabs, "Untitled 1" and "temp 2". Currently, names are changed to a formatted date, so the user needs to guess which one is each one.

Also, currently, after you "Back to separated tabs", tabs are still showing the formatted date and the tab titles are lost. This is not expected for the user, titles should be preserved.

**Comment by Alexey-T** [comment]
Made fix in Git repo. you need to reinstall plugin from Git. 'plugins / addons manager / install from Git', and enter URL
https://github.com/CudaText-addons/cuda_differ/

fix is only partial, it prepends 'old title' to the saved temp filenames. e.g. `Untitled 2_{timestamp}.txt`. I cannot yet hide the timestamp in the pair-view. Nor in the 2 tabs after we return from pair to 2 tabs.

**Comment by Alexey-T** [comment]
Now git repo is updated more. I more carefully restore 'Untitled N' title after returning back from pair to separate tabs.

**Comment by Alexey-T** [comment]
and updated more now. to show pretty tab-title of pair-view with 2 untitled tabs.
