### ISSUE TITLE
Differ should not save a file the user hasn't saved yet

### ISSUE THREAD

**Issue by pintassilgo** [CudaText-addons/cuda_differ#17]
Do a Compare with a never saved file (usually with title `Untitled {number}`, but it may have be renamed by Rename). Then back to separated tabs. If the user do the command to `Save` (usually by pressing Ctrl+S) one of the files that were compared, the usual file prompt to choose location and name should be displayed. Currently, instead, the file is saved in the temporary location it was saved by Differ plugin, under `./differ_backup`. This is not expected for the user.

As I said in #15, the needing of Differ to work with saved files shouldn't be exposed for the user, should only be done under the hood. For the user, a file never saved should remain unsaved and, as reported in #16, the title of a never saved file should also not be changed.

Both this issue and https://github.com/CudaText-addons/cuda_differ/issues/16 were already reported in my comments in https://github.com/CudaText-addons/cuda_differ/issues/15, but I hope now, as separated issues, it gets easier to understand.

**Comment by Alexey-T** [comment]
changed in git. now, after you return to 2 tabs, these tabs are untitled back.
