### ISSUE TITLE
Unsaved files are lost on closing Differ tab

### ISSUE THREAD

**Issue by pintassilgo** [CudaText-addons/cuda_differ#18]
1. Compare two never saved (aka untitled) files.
2. Close the tab showing the diff.

**Actual result:**

The unsaved files are lost forever.

**Expected result:**

Closing a diff tab should have the same effect as "Back to separated tabs", not closing both files. That's what I was used to in Notepad++'s Compare.

If you disagree in enabling that at least as an option, at least user should be warned that unsaved files will be lost.

**Comment by Alexey-T** [comment]
They are saved - in the folder settings/differ_backup.

**Comment by Alexey-T** [comment]
If we will open 2 tabs on closing differ-tab, we won't need
command 'back to separate tabs'

- in tab's context menu,
- nor in Plugins menu

it is OK?

**Comment by veksha** [comment]
Hi @pintassilgo, how can I configure notepad++'s "compare" plugin so it restores tabs?
it asks to save on close.

![image](https://user-images.githubusercontent.com/275333/226174208-06d9a71b-09c0-4f50-a00f-3a4af767773e.png)

**Comment by Alexey-T** [comment]
THis video about NP++ shows that NP++ reopens 2 tabs when you __press toolbar button__. but here in Cud you suggest another thing - reopen 2 tabs when you __close pair tab by X__. different thing!

I find it not handy - reopen 2 tabs when I close pair-tab by X icon. I press X icon to forget about 2 files. if I need these 2 files, I don't press X

**Comment by Alexey-T** [comment]
>The clicked toolbar button is "Clear active compare", which in terms of Cuda Differ is the same as closing the differ tab.

no; in terms of Cuda Differ it's the same as call "Back to separate files".

>When the user closes Cuda Differ, it's reasonable to say it's expected to return to the state from before Cuda Differ started,

"Close tab" - it is good to say user wants to close 2 files. for return back- user has "Back to separate tabs"

**Comment by Alexey-T** [comment]
Can we resolve the issue then?

**Comment by Alexey-T** [comment]
merged to main branch. and added the forced saving of pair-files when you close the tab.
