### ISSUE TITLE
Regression in "Back to separate tabs"

### ISSUE THREAD

**Issue by pintassilgo** [CudaText-addons/cuda_differ#20]
The fix for #18 was creating a new dialog when you try to close a Differ tab, asking if you want to close the compared files or to restore them as separate tabs.

This shouldn't affect the existing "*Back to separate tabs*" command, but it does. The new dialog is displayed when you trigger this command, but it shouldn't, as the user clearly has already chosen to "*Back to separate tabs*".

It's even worse that the dialog has no effect in this case. Even if you choose `Yes` ("*Press Yes to close both files*"), original tabs are restored instead of closed.

---

By the way, the fix for #18 is OK enough, but in my opinion it's not optimal. Instead of asking every time I close a differ tab, I believe the user choice should be stored somewhere and reused in the future. As I suggested in #18, instead of creating the ask dialog, I believe the best approach would be creating the option `differ.separate_on_close` and reading its value to decide what to do when user closes a differ tab.

This is why I was a bit reluctant to close that issue, you even needed to ask "*Can we resolve the issue then?*".

**Comment by CudaText-addons** [comment]
As I see the new dialog (Yes/No msg box) gave problems. it also gave problem when I close Cud - dialog shows, but it's not needed here.
I suggest to revert this dialog, remove it. why do we need this dialog? to not loose files? but they are saved in settings/differ_backup (if files were untitled).

OK to remove this dialog? @pintassilgo @veksha

**Comment by Alexey-T** [comment]
>That's why I suggest to add the option differ.separate_on_close.

Again, this option - if activated - will catch cases "Cud is closing" and "Back to sep tabs is called"! API on_close_pre don't give the 'reason of closing' to plugin. it is hard to add the reason to API (backward compat breaking).

**Comment by Alexey-T** [comment]
>Users are not expected to know that. For users, untitled files are unsaved,

In the case when differ-tab is closed with 1 or 2 untitled tabs , we may show msgbox to user - telling that data has backup.

**Comment by veksha** [comment]
adding new option `differ.separate_on_close` sounds nice. (default value=False)
who wants that behaviour then he will have it.

> In the case when differ-tab is closed with 1 or 2 untitled tabs , we may show msgbox to user - telling that data has backup

why not just ask "do you want to save Untitled1?", and then "do you want to save Untitled2"?
BTW, ctrl+s (File->Save) doesn't work for untitled Differ tabs.

**Comment by Alexey-T** [comment]
>Does Differ really need to close original tabs before it shows the diff

For titled tabs: yes. because a file can be opened only in 1 ui-tab.

**Comment by Alexey-T** [comment]
differ.separate_on_close is ok idea; I can use it on on_close_pre handler, but this handler is always called 

- on closing Cud
- on calling 'Back to separate tabs'

so i am not sure option will be ok.

**Comment by Alexey-T** [comment]
I know what we can do! we can avoid closing of untitled tabs when calling Differ. ie differ will open copy of those tabs (saved to differ_backup).

**Comment by Alexey-T** [comment]
I made this change-- git branch 'dont_close_untitled'. Pls test from git.
@pintassilgo @veksha

**Comment by Alexey-T** [comment]
Ok, i can make named files also NOT closed when calling differ. but then differ-tab will have only COPY of original named file, so user changes in this COPY will be ignored - ie saved to temp dir. it's bad ! user cannot edit original file in differ-tab!

**Comment by Alexey-T** [comment]
What Differ users think about this change? can I open in differ only __copies__ of files, not closing orig files?
@veksha @miroslavmatas @jairomartineza @vavalzar

**Comment by veksha** [comment]
I need to be able to edit and save files directly in pair-tab. this is **big feature**. you can't just remove it! :)

**Comment by Vivalzar** [comment]
I'm afraid I need it too...
________________________________

**Comment by Alexey-T** [comment]
This issue must be solved (1st post)

>The fix for https://github.com/CudaText-addons/cuda_differ/issues/18 was creating a new dialog when you try to close a Differ tab, asking if you want to close the compared files or to restore them as separate tabs.

so what is left?
