### ISSUE TITLE
incorrect jumps in some cases

### ISSUE THREAD

**Issue by CudaText-addons** [CudaText-addons/cuda_differ#7]
![Screenshot from 2023-01-17 10-39-54](https://user-images.githubusercontent.com/4154978/212837765-17b6a1c0-44b6-47bd-94ea-36efce4bc4f5.png)

left side: jmp to prev - works any count of times (loops).
rt side: jmp to prev - stops on 1st match!

@veksha

**Comment by veksha** [comment]
@Alexey-T , please see PR.
